# 抽样
## 常见的概率抽样

| 类别 | 简单随机抽样 | 系统抽样 | 整群抽样 | 分层抽样 | 多阶段抽样 |
| --   | ----         | ----     | ----     | ----     | ----       |
| 概念 | 将全部的观察单位编号，形成抽样框，在抽样框中随机抽取部分观察单位组成样本| 先将总体的观察单位按照某一顺序分成n个部分，再从第一部分随机抽取第k号观察单位，依次用相等间隔，从每一部分各抽取一个观察单位组成样本 | 是以“群”为基本单位的抽样方法，先将总体分成若干群，从中随机抽取一些群，被抽中群内的全部个体组成调查的样本 | 先将总体中全部个体按某种特征分成若干“层”，再从每一层内随机抽取一定数量的个体组成样本 | 将整个抽样过程分成若干阶段进行，在初级抽样单位中抽取二级抽样单位，又在二级抽样单位中抽取三级抽样单位 |
| 优点 | 简单直观；<br>均数（率）及其标准误计算简便 | 易于理解、简便易行；<br>可得到按比例分配的样本；<br>样本在总体中的分布均匀 | 便于组织调查；<br>节约成本；<br>容易控制调查质量 | 抽样误差相对较小；<br>可对不同层采用不同的抽样方法；<br>可对不同层进行独立分析 | 充分利用各种抽样方法的优势，克服各自的不足，并能节省人力、物力 |
| 缺点 | 观察单位较多，编号在实际工作中难以实现；<br>当总体变异大时，抽样误差较分层抽样误差大 | 观察单位按顺序有周期趋势或递增（减）时易产生偏差 | 样本例数一定时，抽样误差大于简单随机抽样（因样本为广泛散布于总体中 | 若分层变量选择不当，层内变异较大，层间变异较小，则分层抽样失去意义 | 在抽样之前要掌握各级调查单位的人口资料及特点 |
| 适用范围 | 是其他抽样方法的基础，主要用于总体不太大的情形 | 主要用于按抽样顺序个体随机分布的情形 | 主要用于群间差异较小的情形 | 主要用于层间差异较大的情形 | 大型流行病学调查 |

**误差大小：** 整群抽样>简单随机抽样>系统抽样>分层抽样

**样本量大小：**整群抽样>简单随机抽样>系统抽样>分层抽样

**概率抽样：**是指每个个体被抽样抽中的概率是非零的、已知的或可计算的。

## 常见的非概率抽样

- 特点
  - 不需要考虑等概率原则
  - 依赖研究人员的经验和专业知识
  - 简便易行、节约资源
  - 结果的稳定性容易受主观影响

| 类别 | 概念 |
| :--: | :------: |
| 偶遇抽样 | 又称便利抽样，指研究者根据实际情况而采用最便利的方法来选取样本，可以抽取偶然遇到的人，或选择那些距离最近的、最容易找到的人作为调查对象 |
| 目的抽样 | 又称判断抽样，指研究者根据研究目标和对情况的主观判断来选择和确定调查对象的方法，是“有目的”地去选择对总体具有代表性的样本 |
| 滚雪球抽样 | 又称链式抽样或网络抽样，指当无法了解总体情形时，可以从能找到的少数个体入手，对他们进行调查，并请他们介绍其他符合条件的人，扩大调查面，如此重复下去直到达到所需的样本量 |
| 定额抽样 |  又称配额抽样，是按照总体的某种特征（年龄、性别、社会阶层等）进行分层（组），然后在每一层（组）中按照事先规定的比例或数量（即定额）用便利抽样或目的抽样的方法选取样本 |
| 空间抽样 | 指对具有空间关联性的各种调查对象及资源进行抽样的一种方法  |

