# 随机事件的概率

不确定的知识+所含不确定性度量的只是=可用的知识

## 随机事件与样本空间

1. 确定性现象（deterministic phenomenon）：在一定条件下必然会发生的现象；
2. 随机现象（random phenomenon）：在同一条件下具有不确定结果的现象。

对随机现象获得一个观察或进行一次测量的过程称为随机试验，简称试验，用$E$表示。

用$\omega$表示试验$E$的一个可能的结果，则称$\omega$位$E$的一个基本事件（elementary event）；基本事件是指不能在分解为更简单结果的事件。

## 事件的运算

1. 包含关系：对任意两事件A和B，如果事件B发生，则事件A必发生，则称事件A包含事件B，记作$A\supseteq B$或$B\subseteq A$，符号$\supseteq$和$ \subseteq$分别表示包含与被包含。
2. 相等关系：如果事件A和事件B满足以下关系：$A\supseteq B 且B\supseteq A$，则称A和B相等，记作$A=B$
3. 事件的和：在一次试验中，对任意两事件A和B，“A和B中至少有一个发生”也是一个事件，称此事件为A和B的“和或并”，记作$A\cup B$，也可以表示为$A+B$。
4. 事件的交：在一次试验中，对任意两事件A和B，“A和B同时发生”也是一个事件，称此事件为A和B的“交”，记作$A\cap B$，也可以表示为$AB$。
5. 事件的差：在一次试验中，“A发生且B不发生”也是一个事件，称此事件为A和B的“差”，记作$A-B$。
6. 互不相容事件：在一次试验中，“A与B不能同时发生”，即$A\cup B=\emptyset$，则称此事件A和事件B为互不相容事件，也称互斥事件。
7. 对立事件：是一种特殊的互不相容事件，若“事件A与事件B不能同时发生，且他们的和组成样本空间”，即$A\cap B=\emptyset 且A\cup B=\Omega$，则称A和B互为对立事件（complementary events）。

## 概率的定义

1. 频率（frequency）：设E为一随机试验，A是其中一事件，在同样条件下把E重复的做n次，以m表示事件A在这n次试验中发生的次数，则称比值$m/n$为事件A发生的频率，记为F(A)：
$$F(A)=\frac{m}{n}$$

2. 概率（probability）：设在同一条件下，重复进行n次试验，随机事件A发生m次，若试验次数n无限大时，频率$m/n$将在某一确定值p的附近摆动，则称p为事件A的概率，记为P(A)：
$$P(A)=p \approx \frac{m}{n}$$

3. 概率有时也被称为相对频率方法；概率是事物固有的属性，不以人的主观意志为转移。
4. 概率的描述性定义
5. 概率的公理化定义：
  - 非负性
  - 规范性
  - 可加可列性

## 概率的加法公式


