# F分布和$\chi^2$分布
## F分布

```{r ,fig.cap="F-distribution Curves",fig.show='hold', fig.align='center', echo=FALSE}
# 设置自由度组合
df_values <- list(c(1, 1), c(2, 1), c(5, 2), c(10, 1), c(100, 100))

# 生成横坐标点
x_values <- seq(0, 5, length.out = 1000)

# 创建数据框
df_data <- expand.grid(x = x_values, df1 = numeric(), df2 = numeric())

# 填充数据框
for (df in df_values) {
  df_data <- rbind(df_data, data.frame(x = x_values, df1 = df[1], df2 = df[2]))
}

# 计算F分布的概率密度
df_data$density <- mapply(function(x, df1, df2) df(x, df1, df2), df_data$x, df_data$df1, df_data$df2)

# 绘制F分布曲线
p <- ggplot(data = df_data, aes(x = x, y = density, color = factor(df1))) +
  geom_line() +
  labs(title = "F-distribution Curves", x = "x", y = "Density", color = "df1") +
  scale_color_discrete(name = "df1") +
  annotate("text", x = c(1, 2, 3, 4, 4.5), y = c(0.8, 1.2, 0.6, 1.2, 0.2), 
           label = c("d1=1, d2=1", "d1=2, d2=1", "d1=5, d2=2", "d1=10, d2=1", "d1=100, d2=100"), 
           color = c("red", "yellow", "green", "blue", "purple"))+
  ylim(0, 2.5)  # 设置y轴范围
            
# 显示图表
print(p)
```

### F分布的应用
1. 方差的同质性检验
组与组之间的差异称组间变异（variation between classes），反映在各组的平均数不同。同一组内部被试（个体）之间的差异称组内变异（variation within class），反映在每一个个体之间的差异。
2. 总变异的分解：
 - 总变异 = 组间变异+组内变异
 - 组间变异 = 实验条件 + 随机误差
 - 组内变异 = 个体差异 + 实验误差 。组内误差都是随机误差。

## $\chi^2$分布

```{r ,fig.cap="Chi-square Distribution Curves",fig.show='hold', fig.align='center', echo=FALSE}
# 设置自由度
df_values <- c(1, 2, 5, 10, 20, 100)

# 生成横坐标点
x_values <- seq(0, 15, length.out = 1000)

# 创建数据框
df_data <- expand.grid(x = x_values, df = df_values)

# 计算卡方分布的概率密度
df_data$density <- dchisq(df_data$x, df_data$df)

# 绘制卡方分布曲线
p <- ggplot(data = df_data, aes(x = x, y = density, color = factor(df))) +
  geom_line() +
  labs(title = "Chi-square Distribution Curves", x = "x", y = "Density", color = "Degrees of Freedom") +
  scale_color_discrete(name = "v:Degrees of Freedom") +
  ylim(0, 1)  # 设置纵轴范围在（0,1）

# 显示图表
print(p)
```

### 卡方检验应用

1. 检验连续变量的分布是否与某种理论分布一致。
2. 检验某个分类变量各类的出现概率是否等于指定概率。
3. 检验某两种方法的结果是否一致。