# 置信区间
## 置信区间与医学参考值范围的辨析
### 标准差与标准误

| 类目 | 标准差 | 均数的标准误 |
| :-: | :------- | :------- |
| 定义 | 描述一组变量的离散程度，并可以作为总体标准差的点估计 | 描述多个样本均数的离散程度，并且是样本均数的标准差估计值 |
| 应用 | 1. 标准差越小，个体资料的离散程度就越小，说明变量值围绕均数分布越紧密，均数的代表性越好 <br> 2.估计医学参考值范围，计算变异系数和标准误 | 1. 标准误越小，统计量的平均抽样误差就越小，说明样本均数和总体均数的平均差异越小，用样本均数估计总体均数的可靠性越大；<br>2. 计算置信区间、进行假设检验|
| 与n的关系 | n越大，样本标准差随机波动的幅度越来越小，并且稳定在总体标准差附近 | n越大，样本均数的标准误越小，并且趋向于0 |
| 控制方法 | 个体差异，不能通过统计方法控制 | 增加n，可以减小标准误 |
| 二者联系 | 1. 两者都是变异指标 <br> 2. 在n相同的情况下，标准差越大，标准误相对越大；标准差越小，标准误也相对越小。正比关系 <br> 3. $\sigma_{\bar x}=\frac{\sigma}{\sqrt{n}}$,$\sigma_{\bar x}$与$\sigma$成正比，与$\sqrt{n}$成反比。|

### 置信区间与医学参考值范围

| 类目 | 总体均数的置信区间 | 医学参考值范围 |
| :-: | :------- | :------- |
| 含义 | 按照预先给定的概率，确定的包含未知总体参数$\mu$（总体均数）的可能范围 | 指特定的“正常”人群（排除了对所研究指标有影响的疾病和有关因素的人群）的生理生化指标中大多数个体的取值所在的范围 |
| 举例 | 若某一样本的均值为10，其95%可信区间为（9.5,10.5），这就表示总体均数介于（9.5,10.5）之间的可信度为95% | 假设空腹血糖95%正常值范围为（3.6,6.1），这就是指95%正常人的空腹血糖值介于（3.6,6.1）之间 |
| 计算 | 1. 总体标准差位置，且样本量n不大，根据t分布计算；<br>2. 总体标准差未知，n足够大，正态近似法；<br>3. 总体标准差已知，根据Z分布计算 | 1. 正态分布法；<br> 2. 偏态分布法 |
| 用途 | 总体均数的区间估计（估计未知的总体均数所在范围 | 1. 个体值的波动范围； <br> 2. 绝大多数观察对象某指标分布范围；<br> 3. 医学判断个体某指标是否正常 |
| 95%理解的常见误区 | | |
| 区别 | | |

## 置信区间的含义与常见说法辨析

1. 在95%置信区间内有95%的总体参数在该区间？×
2. 在95%置信区间内，该区间包含了95%的总体参数？×
3. 以$1-\alpha=95\%$算得的100个可信区间中，平均有95个可信区间包含了总体均数，而另外5个未包含总体均数。√
4. 在95%置信区间，该区间有95%的可能包含总体参数？×
5. 该区间包含总体参数，可信度在95%。√
6. 总体参数有95%的可能落在该区间。×

## 置信区间的两要素及影响因素
### 置信区间的两要素

### 置信区间的影响因素

# 假设检验
## 假设检验的基本步骤
| 步骤 | 内容 |
| :--  | :------ | 
| 建立假设检验，确定检验水准 | 1. 双侧检验：$H_{0}:\mu_{d}=0;H_{1}:\mu_{d}\neq 0,\alpha=0.05$ <br> 2. 单侧检验：$H_{0}:\mu_{d}=0;H_{1}:\mu_{d}<0或\mu_{d}>0,\alpha=0.05$ |
| | 1. 假设检验是针对总体的，而非样本；<br>2. 单双侧检验主要根据专业知识预先确定，并且还需要考虑差异的方向；<br> 3. 单侧检验的检验效能更高。 |
| 计算并选择检验统计量 | 1. 根据研究设计方案、资料类型、样本含量大小及分析目的选用适当的检验方法，并根据样本资料计算相应的检验统计量；<br>2. 不同的检验方法要用不同的公式计算现有样本的检验统计量（$t$检验、$\chi^2$检验、$F$检验）；<br>3. 检验统计量是在$H_{0}$成立的前提下计算的。 |
| 确定P值，做出推断 | 假设检验的统计学结论：<br>1. 若$P\le \alpha$，按所取$\alpha$检验水准，拒绝$H_{0}$，接受$H_{1}$，可以认为...有差异；<br>2. 若$P>\alpha$时，现有样本信息还不足以拒绝H0，尚不能认为...有差异 |
|  | 假设检验所做出的的结论是具有概率性质的，不是绝对的肯定或否定。不论拒绝或不拒绝$H_{0}$都可能发生错误。下结论时，只能两种：<br>1. 两总体有无差异；<br>2. 两样本差异有无统计学意义。|

## 假设检验的两型错误、检验效能
| 客观实际 | 拒绝$H_{0}$，接受$H_{1}$ | 不拒绝$H_{0}$ |
| :--: | :------ | :------ |
| $H_{0}$成立 | $\textrm{I}$型错误($\alpha$)(假阳性) <br>错误拒绝实际成立的$H_{0}$ | 正确推断($1-\alpha$) | 
| $H_{0}$不成立 | 正确推断($1-\beta$)<br>$H_{1}$为真，能够拒绝$H_{0}$的概率称为发现该$H_{1}$的检验效能，用$1-\beta$表示 | $\textrm{II}$型错误($\beta$)(假阴性)<br>不拒绝实际不成立的$H_{0}$ |

### $1-\beta$的影响因素：
1. 检验水准$\alpha$（正向）——检验水准$\alpha$越大，检验效能越大
2. $H_{0}$与$H_{1}$的差异大小（正向）——差异越大，检验效能越大
3. 样本量（正向）——样本量越大，检验效能越大
4. 标准差越大（反向）——个体差异（标准差）越小，检验效能越大
5. 单双侧检验：单侧检验效能高于双侧检验效能

### $\alpha 、\beta 、1-\beta$关系：
1. 当样本量确定时，$\alpha$与$\beta$呈反向变化关系，与$1-\beta$呈正向变化关系。如果把$\alpha$设置得很小，势必增加犯$\textrm{II}$型错误的概率，从而降低检验效能；反之，如果把重点放在减少$\beta$上，势必增加犯$\textrm{I}$型错误的概率，从而降低了置信度。
2. 要同时减小$\alpha$和$\beta$，只有通过增加样本含量来计算。

## 假设检验与置信区间的关系

| 基本思想 | 假设检验 | 置信区间 |
| :--:    | :------  | :------ |
| 基本思想 | 假设检验的假设是指我们对总体特征（如参数、分布）的某种推测，从而用概率来判断样本数据所提供的的信息和我们对总体特征猜想的一致性，进而结合专业知识判断这一猜想的正确性 | 置信区间是指有样本统计量所构造的总体参数的估计区间，区间估计是按照一定的概率和可信度$(1-\alpha)$用一个区间估计总体参数所在的范围，这个范围称作可信度为$(1-\alpha)$的可信区间 |
| 区别 | 1. 假设检验用于推断总体参数之间是否不同 | 1. 置信区间用于推断总体参数所在范围；<br> 2.置信区间比假设检验提供更多的信息，置信区间能够回答假设检验的问题；<br> 3. 置信区间在回答差别有无统计学意义时，还可以提示差别是否具有实际意义。 |
| 联系  | 1. 假设检验与置信区间都属于统计推断方法；<br>2. 置信区间估计总体参数所采用的的统计量与假设检验的检验统计量相同； | 3.置信区间能够回答假设检验的问题。根据置信度$1-\alpha$构造置信区间，如果统计量在置信区间内，那么不拒绝原假设；如果不在置信区间中，那么拒绝原假设；<br>4. 双侧检验时，置信区间确定的$z'$与检验水准$\alpha$确定的检验统计量的分布界值相同，因此，在双侧检验时$C=1-\alpha$。根据显著水平$\alpha$，可以构造置信度为$1-\alpha$的置信区间  |