# 非参数检验
## 卡方检验
### 分类资料差异比较的方法

| 资料特征 | 数据特征 |     | 完全随机设计 | |配对设计 | 随机区组 |
| :--:   | :--:     | :---- | :----  | :---- | :---- | :---- |
|  |  | 单组 | 两组 | 多组 | | |
| 分类资料 | 无序分类资料 | 二项分布直接计算概率法、正态近似法（Z检验）、率的正态近似 | 独立四格表$\chi^2$检验、Fisher确切概率法 | R×C交叉表$\chi^2$检验、Fisher确切概率法 | 配对四格表$\chi^2$检验，配对R×R列联表$\chi^2$检验 | / |
| | 等级资料 | Wilcoxon符合秩和检验 | wilcoxon秩和检验 | Kruskal-Wallis H检验 | Wilcoxon符合秩和检验 | Friedman M秩和检验 | 

### 单个率的比较
| 方法 | 内容   | 
| :--: | ------ |
| 确切概率法  | 1. 适用情形：样本量较小或$\pi_0$不靠近0.5时作单侧检验的情形。<br>2. 计算公式：<br>(1)最多有k例阳性的概率：$Pr(X\le k)$<br>(2)最少有k例阳性的概率：$Pr(X\ge k)$ |
| 正态近似法 | 1. 适用情形：样本量较大时，$n\pi,n(1-\pi)$均大于5；<br>2. 计算公式：分子为$p-\pi_0$，分母为率的标准误 |
*notice：*上式中p为样本率，$\pi_0$为给的总体率（常为理论值或标准值），n为样本含量。

## 率的比较
### 2×2交叉表数据的$\chi^2$检验
| 方法 | 情形  | 计算公式 | 
| :--: | :---- | :----    |
| 独立四格表卡方检验 | $n\ge 40$且所有的$T\ge 5$<br>$n\ge 40$且任一理论频数有$1\le T< 5$<br>当$n<40$，或任一一个格子理论频数$T<1$时 | 卡方基本公式、独立四格表专用公式<br>同上、但是需要校正<br>用四格表资料的Fisher确切概率法 |
| 正态近似法 | $n_1p_1,n_1(1-p_1),n_2p_2,n_2(1-p_2)$均大于5 | 分子为样本率之差，分母为样本率差的标准误<br>$S_{p1-p2}$为两个样本率之差的标准误，$p_c=\frac{x_1+x_2}{n_1+n_2}$为两样本的合并率 |
| 校正样本率的正态近似法 | 当$n_1p_1,n_1(1-p_1),n_2p_2,n_2(1-p_2)$不太大时 | 同上，但是需要对样本率实施“分子+2、分母+4”的校正  |

*notice：*

1. 正态近似法与卡方检验结果是很接近的。在日常计算时，因为计算简便，故常用卡方检验公式。
2. 四格表的自由度为1。
3. 四格表实际频数变动时，若周边合计数保持不变，则理论频数将不会产生变化。
4. 用$n_R$和$n_C$和n分别表示行合计、列合计和总合计，则计算每格理论数的公式为：$T_{RC}=\frac{n_R×n_C}{n}$。
5. $\chi^2$检验的基本公式：$\chi^2=\sum \frac{(A-T)^2}{T}$。
6. 校正的$\chi^2$检验的基本公式：$\chi^2=\sum \frac{(|A-T|-0.5)^2}{T}$。

### 配对设计数据的$\chi^2$检验
| 方法 | 情形 | 计算公式 | 
| :---: | :---- | :---- |
| 配对四格表卡方检验 | 当$(b+c)\ge 40$时<br>当$(b+c)<40$时 |配对卡方检验专用公式<br>校正配对卡方检验专用公式 |
| 配对R×R交叉表数据的$\chi^2$检验 | R（$R\ge2$） | $T=\frac{k-1}{k}\sum_{i=1}^{k}\frac{(n_i-m_i)^2}{n_i+m_i-2A_{ii}}$ |

*notice：*

1. 配对$\chi^2$检验的基本公式：$\chi^2=\sum \frac{(A-T)^2}{T}=\frac{(b-c)^2}{b+c}$。
2. 若b+c<40,使用校正的配对$\chi^2$检验的基本公式：$\chi^2=\sum \frac{(|b-c|-1)^2}{b+c}$。

## 独立性检验
### 2×2交叉表的独立性检验

1. 建立假设检验，确定检验水准
$H_0$:两变量之间相互独立
$H_1$:两变量之间相互独立
$\alpha=0.05$
2. 计算检验统计量
\[\chi^2=\sum_{i,j}\frac{(A_{ij}-T_{ij})^2}{T_{ij}}
\]
3. 确定P值，做出推断
4. 关联系数的计算
\[r=\sqrt{\frac{\chi^2}{\chi^2+n}}\]

### 2×2配对数据的独立性检验
### R×C样本率或构成比的比较

| 类目 | 内容 |
| :--: | :------ |
| 假设检验 | $H_0$：各组总体率（或构成比）相同。$H_1$：各组总体率（或构成比）不同（不全相同）。 |
| 计算公式 | 卡方检验基本公式，自由度为：$v=(R-1)(C-1)$ |
| 数据要求 | 1. 应用条件：不能有理论频数小于1的格子，或者不能有1/5以上的理论频数大于等于1且小于5 <br>2. 不能进行卡方检验时的解决办法：①增加样本量；②合并或删除理论频数比较小的行或列；③采用Fisher确切概率法 | 
| 卡方分割 | 多个率或多个频率分布比较的卡方检验，当结论为拒绝$H_0$时，仅表示多组之间是有差别的。若需要明确研究是那两组之间存在差别，可做率的多重比较，将R×C表分割为若干个小的四格表进行检验，并且需要根据比较的次数合理地修正检验水准$\alpha$，否则将人为地增大犯第一类错误的概率 |

*notice:*

1. 多个独立样本率的比较，根据R个独立样本的频率分布，是检验R个二项分布总体的概率是否相同，。假设对四个样本率进行比较，进行$\chi^2$检验，则它的行数为4，列数为2，其自由度为$v=(R-1)×(C-1)=(4-1)(2-1)=3$。
2. 针对行列表资料的$\chi^2$检验，若有$1/5$格子以上的理论频数小于5，即$1\le T\le5$时，应考虑增加样本量，或结合专业知识对行或列进行合并。

## 秩和检验 



