--- 
title: "卫生统计学笔记"
author: "Zhoulvbang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography:
- book.bib
- packages.bib
description: |
  这是一个使用rmarkdown制作，用GitHub托管，由www.lazyzhou.cn进行展示的卫生统计学笔记。
  在终极的分析中，一切知识都是历史
  在抽象的意义下，一切科学都是数学
  在理性的基础上，所有的判断都是统计学
  艰难修补与完善。
  
link-citations: true
# github-repo: "rstudio/bookdown-demo"
github-repo: "zhoulvbang/zhoulvbang.github.io"
output: 
  html_document: 
    toc: true
    keep_md: true
    css: style.css
---

```{r setup, include=FALSE}
library(ggplot2) #用于绘图
library(gridExtra) #分格
library(cowplot) 
library(bookdown)
library(rmarkdown)

library(showtext) #如果你系统中没有中文字体，或者想要使用更好的中文显示效果，可以使用 showtext 包。

# 加载knitr和reticulate包
library(knitr) #一个动态报告生成工具，它允许用户将 R 代码嵌入到文档（如 R Markdown、LaTeX、HTML、Markdown）中，并生成包含代码、文本、图形和输出结果的报告。
library(reticulate)  #是一个 R 和 Python 的接口包，它允许用户在 R 环境中运行 Python 代码，并实现 R 和 Python 之间的无缝数据交换。

# 设置knitr全局选项
knitr::opts_chunk$set(
  echo = TRUE,  # 是否显示代码
  eval=TRUE, #是否编译代码框内的代码
  highlight=TRUE, #实现语法高亮
  warning = FALSE,  # 是否显示警告
  message = FALSE,  # 是否显示信息
  fig.width = 7,  # 图形宽度
  fig.height = 5  # 图形高度
)

# 使用特定的Python环境（请根据实际路径修改）
#use_python("/Users/simonzhou/anaconda3/bin/python3", required = TRUE)
use_python("C:/Users/asus/AppData/Local/Programs/Python/Python39/python.exe", required = TRUE)
#python_path <- system("which python3", intern = TRUE)
#use_python(python_path, required = TRUE)
#RMarkdown文档中自动查找并设置Python路径
```

# About(关于)

这是一个用**Markdown**编写的 _小周的学习笔记_ 书籍。您可以使用Pandoc的Markdown支持的任何内容；例如，数学方程式 $a^2 + b^2 = c^2$。

  “All knowledge is, in final analysis, history.

All sciences are, in the abstact, mathematics.

All judgements are, in their rationale, statistics.”

  “在终极的分析中，一切知识都是历史
  
  在抽象的意义下，一切科学都是数学
  
  在理性的基础上，所有的判断都是统计学”
  
  ——C.R. Rao *Statistics And Truth*

<!--chapter:end:index.Rmd-->


# 关于卫生统计学

Placeholder


## 卫生统计学：介绍与展望
### 什么是卫生统计学？
### 卫生统计学的重要性
### 卫生统计学的未来展望
### 结语

<!--chapter:end:01-About-health-statistics.Rmd-->


# 不同资料的统计描述

Placeholder


## 定量资料的描述指标
### 集中趋势指标
### 均数、中位数和众数大小的关系变化
## 离散数据的描述指标
### 离散趋势指标
## 分类资料的描述指标
### 分类资料的统计描述指标
### 动态数列
### 应用相对数的注意事项
## 率的标准化
## 常见统计图
### 资料类型
### 统计图使用类型及目的
### 统计图的选择
## 常见的概率抽样
## 常见的非概率抽样

<!--chapter:end:02-descriptive-statistics.Rmd-->

# 待定

一切都是最好的安排

<!--chapter:end:03-Random-events-probabilities.Rmd-->


# 离散型随机变量的概率分布

Placeholder


## 二项分布(Binomial Distribution)
## 泊松分布(Poission Distribution)
## 二项分布的应用
## 泊松分布的应用

<!--chapter:end:04-discrete-type-random-variable.Rmd-->


# 连续型随机变量的概率分布

Placeholder


## 正态分布(Normal Distribution)
## 标准正态分布
### 正态分布、标准正态分布的应用
### 正负偏态分布
## 小结
## t分布
## F分布
### F分布的应用
## $\chi^2$分布
### 卡方检验应用

<!--chapter:end:05-random-variable-of-continuous-type.Rmd-->


# 参数估计

Placeholder


## 样本量的抽样分布
## 样本均数及其抽样分布
## 中心极限定理
## 小结

<!--chapter:end:06-parameter-estimation.Rmd-->


# 定量资料与分类资料的分析步骤

Placeholder


## 定量资料的分析步骤
## 分类资料的分析步骤
## 经典例题
### 经典例题1
### 经典例题2

<!--chapter:end:07-analytical-procedure.Rmd-->


# 置信区间

Placeholder


## 置信区间与医学参考值范围的辨析
### 标准差与标准误
### 置信区间与医学参考值范围
## 置信区间的含义与常见说法辨析
## 置信区间的两要素及影响因素
### 置信区间的两要素
### 置信区间的影响因素
## 假设检验的基本步骤
## 假设检验的两型错误、检验效能
### $1-\beta$的影响因素：
### $\alpha 、\beta 、1-\beta$关系：
## 假设检验与置信区间的关系

<!--chapter:end:08-confidence-interval.Rmd-->


# 参数检验

Placeholder


## 参数检验和非参数检验的区别
## $t$分布
## 方差分析
### 完全随机设计的方差分析
### 随机区组设计的方差分析

<!--chapter:end:09-parameter-test.Rmd-->


# 非参数检验

Placeholder


## 卡方检验
### 分类资料差异比较的方法
### 单个率的比较
## 率的比较
### 2×2交叉表数据的$\chi^2$检验
### 配对设计数据的$\chi^2$检验
## 独立性检验
### 2×2交叉表的独立性检验
### 2×2配对数据的独立性检验
### R×C样本率或构成比的比较
## 秩和检验 
## 两变量关系分析
## 常见相关系数
### 直线相关分析基本流程
### 三类相关系数总结
## 简单直线回归
### 直线回归分析的基本流程
## 直线相关与直线回归的比较

<!--chapter:end:10-non-parameter-test.Rmd-->


# Usage(用法) 

Placeholder


## Render book(渲染这本书)
## Preview book(预览这本书)
## 安装R+Rstudio
## 创建一个Rmarkdown文件
### 首先我们要安装一个专门的包`bookdown`
### 在set部分load `bookdown`
### 其他宏包的需求与使用
### 创建一个`bookdown`文件
## 代码块的选项设置（options）
### 输出信息选项
### 错误信息选项
### 全局设置
## 在vscode中编辑rmarkdown
### 安装R extension
### 安装其他的软件
#### 安装Pandoc
#### 检查Pandoc路径：
#### 指定Pandoc路径：
## 与Rmarkdown的缘分
## 关于引用

<!--chapter:end:11-Usage.Rmd-->

