---
title: "随机事件的概率"
author: "Simonzhou"
date: "2025-02-23"
format: 
  html:           # 输出格式为 HTML
    self-contained: true  # 生成独立的 HTML 文件
  pdf:            # 可选：如果需要 PDF 输出
    default
execute:
  echo: true      # 在输出中显示代码
  eval: true      # 执行代码
  warning: false  # 隐藏警告信息
  message: false  # 隐藏消息
---

# 随机事件的概率

不确定的知识+所含不确定性度量的知识=可用的知识

## 随机事件与样本空间

1.  确定性现象（deterministic phenomenon）：在一定条件下必然会发生的现象；
2.  随机现象（random phenomenon）：在同一条件下具有不确定结果的现象。

对随机现象获得一个观察或进行一次测量的过程称为随机试验，简称试验，用$E$表示。

用$\omega$表示试验$E$的一个可能的结果，则称$\omega$为$E$的一个基本事件（elementary event）；基本事件是指不能在分解为更简单结果的事件。

## 事件的运算

1.  包含关系：对任意两事件A和B，如果事件B发生，则事件A必发生，则称事件A包含事件B，记作$A\supseteq B$或$B\subseteq A$，符号$\supseteq$和 $\subseteq$分别表示包含与被包含。
2.  相等关系：如果事件A和事件B满足以下关系：$A\supseteq B 且B\supseteq A$，则称A和B相等，记作$A=B$
3.  事件的和：在一次试验中，对任意两事件A和B，“A和B中至少有一个发生”也是一个事件，称此事件为A和B的“和或并”，记作$A\cup B$，也可以表示为$A+B$。
4.  事件的交：在一次试验中，对任意两事件A和B，“A和B同时发生”也是一个事件，称此事件为A和B的“交”，记作$A\cap B$，也可以表示为$AB$。
5.  事件的差：在一次试验中，“A发生且B不发生”也是一个事件，称此事件为A和B的“差”，记作$A-B$。
6.  互不相容事件：在一次试验中，“A与B不能同时发生”，即$A\cup B=\emptyset$，则称此事件A和事件B为互不相容事件，也称互斥事件。
7.  对立事件：是一种特殊的互不相容事件，若“事件A与事件B不能同时发生，且他们的和组成样本空间”，即$A\cap B=\emptyset 且A\cup B=\Omega$，则称A和B互为对立事件（complementary events）。

## 概率的定义

1.  频率（frequency）：设E为一随机试验，A是其中一事件，在同样条件下把E重复的做n次，以m表示事件A在这n次试验中发生的次数，则称比值$m/n$为事件A发生的频率，记为F(A)： $$F(A)=\frac{m}{n}$$

2.  概率（probability）：设在同一条件下，重复进行n次试验，随机事件A发生m次，若试验次数n无限大时，频率$m/n$将在某一确定值p的附近摆动，则称p为事件A的概率，记为P(A)： $$P(A)=p \approx \frac{m}{n}$$

3.  概率有时也被称为相对频率方法；概率是事物固有的属性，不以人的主观意志为转移。

4.  概率的描述性定义

5.  概率的公理化定义：

-   非负性:对于任意事件A，有$P(A)\geq 0$
-   规范性:$P(\Omega)=1$
-   可加可列性:$P(\bigcup \limits_{i=1}^{\infty}A_i)=\sum \limits_{i=1}^{\infty}P(A_i)$

## 概率的加法公式

若A和B是样本空间$\Omega$中两个互不相容的事件，则事件和的概率等于两事件概率之和，即：

$$P(A+B)=P(A)+P(B)$$ 这称之为概率的加法公式。此公式要求事件A和事件B互不相容。

易知，A的对立事件$\bar A$的概率$P(\bar A)=1-P(A)$，加法公式可自然推广到多个事件的情形。

对于任意事件A和B，即事件A和不是互不相容，更一般有： $$P(A+B)=P(A)+P(B)-P(AB)$$ 因为当A和B互不相容时，有$P(AB)=0$。

## 概率的乘法公式

当存在某些可能影响结果的条件时，事件发生的概率可能会改变，我们称这种情况下的概率为条件概率。

1.  条件概率

在已知事件A发生的条件下，事件B发生的概率成为条件概率（conditional probability），记为$P(B\mid A)$，公式为： $$P(B\mid A)=\frac{P(AB)}{P(A)},P(A)>0$$ 即条件概率等于事件A和B同时发生的概率除以事件A发生的概率。

2.  概率乘法公式

$$P(AB)=P(A)P(B\mid A),P(A)>0\\
P(AB)=P(B)P(A\mid B),P(B)>0$$

3.  独立事件

如果事件B发生的概率不受事件A发生概率的影响，即$P(B\mid A)=P(B)$，则称事件B对事件A独立。由于两事件间的独立总是相互的，故也有$P(A\mid B)=P(A)$。

根据$P(AB)=P(B)P(A\mid B),P(B)>0$，若事件A、B独立，则有 $$P(AB)=P(A)P(B)$$

在医学研究中，可以根据试验条件及生物学知识判断事物之间的独立性。

## 全概率公式与Bayes公式

1.  全概率公式

如果事件组$A_1,A_2,\dots,A_n$满足以下两个条件：

-   $A_1,A_2,\dots,A_n$互不相容，且$P(A_i)>0(i=1,2,\dots,n)$;
-   $A_1+A_2+\dots+A_n=\Omega$

那么对于任意事件B，都有

$$P(B)=\sum_\limits{i=1}^{n}P(A_i)P(B\mid A_i)$$

此公式成为全概率公式（total probability formula），即B的概率可以表示为在给定$A_i$发生条件下B发生的条件概率的加权平均。

2.  Bayes公式

对于n个互不相容的事件$A_1,A_2,\dots,A_n$，且他们的和为必然事件，则在时间B发生的前提下事件$A_k(k=1,2,\dots,n)$发生的概率为：

$$P(A_k\mid B)=\frac{P(A_k)P(B\mid A_k)}{\sum_\limits{i=1}^{n}P(A_i)P(B\mid A_i)},(k=1,2,\dots,n),P(B)>0$$

Bayes公式的意义在于，它可以改变条件概率结论的方向，即在知道结果的情况下来推断原因，用式子$P(A_k\mid B)$表示，称为后验概率(posterior probability)；而$P(A_k)$表示各种原因出现可能性的大小，一般是过去经验的总结，称为先验概率(prior probability)。

### Bayes方法

在流行病学领域，研究人员一直在寻找提高分析准确性和可靠性的方法。一种越来越流行的方法是使用贝叶斯方法，该方法为处理复杂数据和整合先验知识提供了独特的视角。

1.  为什么使用贝叶斯方法？

贝叶斯方法允许流行病学家纳入关于该疾病的现有知识或信念或风险因素纳入分析，从而获得更准确、更翔实的结果。

2.  处理复杂模型

贝叶斯方法非常适合分析复杂的流行病学模型具有许多参数和相互作用，因为它们可以解释这些参数的不确定性。

3.  处理缺失数据

贝叶斯方法可以将缺失数据视为另一个需要估计的未知参数来处理，与排除或归咎于缺失数据的传统方法相比，这可以产生更准确的结果。

4.  提供概率解释

贝叶斯方法以概率分布的形式提供结果，比频率学派方法获得的点估计和置信区间更直观、更具信息量。

### 流行病学中的Bayes应用

在人卫版《流行病学》第8版中，第七章-筛检，关于预测值的计算，该指标反映了筛检试验实际应用到人群筛查后，获得的首医收益大小。

在医院开展的基于病例-非病例设计的筛查试验研究，病例组和非病例组的构成比不能代表目标人群的现患与未患比例，因此不能直接计算预测值。此时，可以根据灵敏度、特异度、现患率与预测值的关系式（Bayes公式）来估算预测值。

\[PPV=\frac{SE\times P}{SE\times P+(1-P)(1-SP)}\] \[NPV=\frac{SP\times (1-P)}{SP\times (1-P)+(1-SE)\times P}\]

公式中，PPV是阳性预测值，NPV是阴性预测值；SE是灵敏度，SP是特异度，P是患病率。

[流行病学中的贝叶斯方法:简介](https://www.editverse.com/zh-CN/%E6%B5%81%E8%A1%8C%E7%97%85%E5%AD%A6%E4%B8%AD%E7%9A%84%E8%B4%9D%E5%8F%B6%E6%96%AF%E6%96%B9%E6%B3%95%E7%AE%80%E4%BB%8B/)