---
title: "方差分析"
author: "Simonzhou"
date: "2025-02-25"
format: 
  html:           # 输出格式为 HTML
    self-contained: true  # 生成独立的 HTML 文件
  pdf:            # 可选：如果需要 PDF 输出
    default
execute:
  echo: true      # 在输出中显示代码
  eval: true      # 执行代码
  warning: false  # 隐藏警告信息
  message: false  # 隐藏消息
---

# 方差分析

## 完全随机设计的方差分析

| 类目 | 完全随机设计的方差分析 |
|:-------------------------:|:--------------------------------------------|
| 数据要求 | 独立性、正态性、方差齐性 |
| 检验目的 | 推断多个样本所代表的总体均数是否不等 |
| $H_0$与$H_1$ | $H_0$:$\mu_1=\mu_2=\dots =\mu_a$，各组所代表的总体均数相等。$H_1$:$\mu_1,\mu_2,\dots,\mu_a$各组总体均数不全相等（至少有一个不等式成立） |
| 检验统计量 | $F=\frac{MS_{组间}}{MS_{组内}}\sim(v_{组间}=k-1，v_{组内}=n-k）$ |
| 关键要点 | 总变异分解为组间变异和组内变异 |

## 随机区组设计的方差分析

| 类目 | 随机区组设计的方差分析 |
|:---------------------:|:------------------------------------------------|
| 数据要求 | 处理组间、区组间数据满足独立、正态性和方差齐性 |
| 处理组假设 | $H_0$：不同处理组水平的均数相同；$H_1$：不同处理组水平的均属不全相同 |
| 区组假设 | $H_0$：不同区组对观测指标的影响很大；$H_1$：不同区组对观测指标的影响不全相同 |
| 检验统计量 | $F=\frac{MS_{处理}}{MS_{误差}}\sim(v_{处理}=k-1,v_{误差}=(b-1)×(k-1))$<br>$F=\frac{MS_{区组}}{MS_{误差}}\sim(v_{区组}=k-1,v_{误差}=(b-1)×(k-1))$ |
| 关键要点 | 总变异分解为处理组变异、区组变异和随机误差变异 |

## 析因设计

## 析因设计的总结

| 类目 | 析因设计的方差分析 |
|:----------------:|:-----------------------------------------------------|
| **数据要求** | 因素之间的数据独立，样本数据满足正态性和方差齐性假设 |
| **检验目的** | 推断多个因素及其交互作用是否对观测指标存在显著影响 |
| **主效应假设** | $H_0$: 各因素的水平对观测指标的均数无显著影响；<br>$H_1$: 各因素的水平对观测指标的均数存在显著影响 |
| **交互作用假设** | $H_0$: 不同因素水平的交互作用对观测指标的均数无显著影响；<br>$H_1$: 不同因素水平的交互作用对观测指标的均数存在显著影响 |
| **检验统计量** | $F=\frac{MS_{主效应或交互作用}}{MS_{误差}}\sim F(v_{效应},v_{误差})$ |
| **关键要点** | \- 总变异分解为主效应变异、交互作用变异和随机误差变异<br>- 各因素主效应和交互作用的显著性需要单独检验<br>- 每个因素包含多个水平，可能是固定效应或随机效应 |